#!/bin/bash

set -e

appStart () {

  /usr/bin/polipo -c /etc/polipo/config

}

appHelp () {
  echo "Available options:"
  echo "  app:start          - Starts polipo (default)"
  echo "  app:help           - Displays the help"
  echo "  [command]          - Execute the specified linux command eg. bash"
}

case "$1" in
  app:start)
    appStart
    ;;
  app:help)
    appHelp
    ;;
  *)
    if [ -x $1 ]; then
      $1
    else
      prog=$(which $1)
      if [ -n "${prog}" ] ; then
        shift 1
        $prog $@
      else
        appHelp
      fi
    fi
    ;;
esac

exit 0
